server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

dubbo:
  application:
    name: dubbo-consumer

  registry:
    address: zookeeper://zookeeper:2181