version: '3.8'

services:
  redis:
    image: redis:7
    container_name: demo-redis
    ports:
      - "6379:6379"
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - redis_data:/data
    networks:
      - demo-network

volumes:
  redis_data:

networks:
  demo-network:
    driver: bridge
